using System.Collections.Generic;

namespace Nixill.GTFS
{
  internal class DayMasks
  {
    private static readonly string[] Outputs = new string[] {
      "never",
      "Monday",
      "Tuesday",
      "Monday and Tuesday",
      "Wednesday",
      "Monday and Wednesday",
      "Tuesday and Wednesday",
      "Monday through Wednesday",
      "Thursday",
      "Monday and Thursday",
      "Tuesday and Thursday",
      "Monday, Tuesday, and Thursday",
      "Wednesday and Thursday",
      "Monday, Wednesday, and Thursday",
      "Tuesday through Thursday",
      "Monday through Thursday",
      "Friday",
      "Monday and Friday",
      "Tuesday and Friday",
      "Monday, Tuesday, and Friday",
      "Wednesday and Friday",
      "Monday, Wednesday, and Friday",
      "Tuesday, Wednesday, and Friday",
      "Monday through Wednesday and Friday",
      "Thursday and Friday",
      "Monday, Thursday, and Friday",
      "Tuesday, Thursday, and Friday",
      "Monday, Tuesday, Thursday, and Friday",
      "Wednesday through Friday",
      "Wednesday through Friday and Monday",
      "Tuesday through Friday",
      "Monday through Friday",
      "Saturday",
      "Monday and Saturday",
      "Tuesday and Saturday",
      "Monday, Tuesday, and Saturday",
      "Wednesday and Saturday",
      "Monday, Wednesday, and Saturday",
      "Tuesday, Wednesday, and Saturday",
      "Monday through Wednesday and Saturday",
      "Thursday and Saturday",
      "Monday, Thursday, and Saturday",
      "Tuesday, Thursday, and Saturday",
      "Monday, Tuesday, Thursday, and Saturday",
      "Wednesday, Thursday, and Saturday",
      "Monday, Wednesday, Thursday, and Saturday",
      "Tuesday through Thursday and Saturday",
      "Monday through Thursday and Saturday",
      "Friday and Saturday",
      "Monday, Friday, and Saturday",
      "Tuesday, Friday, and Saturday",
      "Monday, Tuesday, Friday, and Saturday",
      "Wednesday, Friday, and Saturday",
      "Monday, Wednesday, Friday, and Saturday",
      "Tuesday, Wednesday, Friday, and Saturday",
      "Monday through Wednesday, Friday, and Saturday",
      "Thursday through Saturday",
      "Thursday through Saturday and Monday",
      "Thursday through Saturday and Tuesday",
      "Thursday through Saturday, Monday, and Tuesday",
      "Wednesday through Saturday",
      "Wednesday through Saturday and Monday",
      "Tuesday through Saturday",
      "Monday through Saturday",
      "Sunday",
      "Monday and Sunday",
      "Tuesday and Sunday",
      "Sunday through Tuesday",
      "Wednesday and Sunday",
      "Monday, Wednesday, and Sunday",
      "Tuesday, Wednesday, and Sunday",
      "Sunday through Wednesday",
      "Thursday and Sunday",
      "Monday, Thursday, and Sunday",
      "Tuesday, Thursday, and Sunday",
      "Sunday through Tuesday and Thursday",
      "Wednesday, Thursday, and Sunday",
      "Monday, Wednesday, Thursday, and Sunday",
      "Tuesday through Thursday and Sunday",
      "Sunday through Thursday",
      "Friday and Sunday",
      "Monday, Friday, and Sunday",
      "Tuesday, Friday, and Sunday",
      "Sunday through Tuesday and Friday",
      "Wednesday, Friday, and Sunday",
      "Monday, Wednesday, Friday, and Sunday",
      "Tuesday, Wednesday, Friday, and Sunday",
      "Sunday through Wednesday and Friday",
      "Thursday, Friday, and Sunday",
      "Monday, Thursday, Friday, and Sunday",
      "Tuesday, Thursday, Friday, and Sunday",
      "Sunday through Tuesday, Thursday, and Friday",
      "Wednesday through Friday and Sunday",
      "Wednesday through Friday, Monday, and Sunday",
      "Tuesday through Friday and Sunday",
      "Sunday through Friday",
      "Saturday and Sunday",
      "Saturday through Monday",
      "Tuesday, Saturday, and Sunday",
      "Saturday through Tuesday",
      "Wednesday, Saturday, and Sunday",
      "Saturday through Monday and Wednesday",
      "Tuesday, Wednesday, Saturday, and Sunday",
      "Saturday through Wednesday",
      "Thursday, Saturday, and Sunday",
      "Saturday through Monday and Thursday",
      "Tuesday, Thursday, Saturday, and Sunday",
      "Saturday through Tuesday and Thursday",
      "Wednesday, Thursday, Saturday, and Sunday",
      "Saturday through Monday, Wednesday, and Thursday",
      "Tuesday through Thursday, Saturday, and Sunday",
      "Saturday through Thursday",
      "Friday through Sunday",
      "Friday through Monday",
      "Friday through Sunday and Tuesday",
      "Friday through Tuesday",
      "Friday through Sunday and Wednesday",
      "Friday through Monday and Wednesday",
      "Friday through Sunday, Tuesday, and Wednesday",
      "Friday through Wednesday",
      "Thursday through Sunday",
      "Thursday through Monday",
      "Thursday through Sunday and Tuesday",
      "Thursday through Tuesday",
      "Wednesday through Sunday",
      "Wednesday through Monday",
      "Tuesday through Sunday",
      "daily"
    };

    internal static string Get(int input)
    {
      return Outputs[input % 128];
    }
  }
}